import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/ui/theme-provider';
import type { Metadata } from 'next';
import { IBM_Plex_Mono, Lora, Cormorant_Infant } from 'next/font/google';
import './globals.css';

const loraSans = Lora({
  variable: '--font-sans',
  subsets: ['latin', 'cyrillic-ext'],
});
const ibmPlexMono = IBM_Plex_Mono({
  variable: '--font-mono',
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['cyrillic-ext', 'latin-ext'],
});
const CormorantInfantSerif = Cormorant_Infant({
  variable: '--font-serif',
  weight: ['400', '700'],
  subsets: ['cyrillic-ext', 'latin-ext'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${CormorantInfantSerif.variable} ${loraSans.variable} ${ibmPlexMono.variable}  antialiased`}
    >
      <body
      // className={`${CormorantInfantSerif.variable} ${loraSans.variable} ${ibmPlexMono.variable}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster closeButton position="bottom-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
